make:
	g++ client.cpp GUI/*.cpp GUI/Login/*.cpp GUI/Menu/*.cpp GUI/ListApp/*.cpp GUI/TreeFolder/*.cpp GUI/ListProcess/*.cpp GUI/KeyLogger/*.cpp -pthread FUNCTION/*.cpp -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -lncurses -o ui
